=== knejadshamsi/ez-backend-turbo/src/main/resources/matsim-input/dtd/config_v2.dtd
<!-- MATSim Config DTD v2.0 -->

<!ELEMENT config (module)*>

<!ELEMENT module (param|parameterset)*>
<!ATTLIST module
    name CDATA #REQUIRED>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param
    name  CDATA #REQUIRED
    value CDATA #IMPLIED>

<!ELEMENT parameterset (param|parameterset)*>
<!ATTLIST parameterset
    type CDATA #REQUIRED>

=== knejadshamsi/ez-backend-turbo/input/config.xml
<?xml version="1.0" ?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>
    <!-- Simulation-wide global configuration parameters -->
    <module name="global">
        <param name="randomSeed" value="4711" />
        <param name="coordinateSystem" value="Atlantis" />
        <param name="numberOfThreads" value="1" />
    </module>

    <!-- Input file specifications for network, population, and vehicle types -->
    <module name="network">
        <param name="inputNetworkFile" value="network.xml" />
    </module>

    <module name="plans">
        <param name="inputPlansFile" value="population.xml" />
    </module>

    <module name="vehicles">
        <param name="vehiclesFile" value="vehicle_types.xml" />
    </module>

    <!-- Detailed queue simulation configuration -->
    <module name="qsim">
        <param name="startTime" value="00:00:00" />
        <param name="endTime" value="30:00:00" />
        <param name="flowCapacityFactor" value="1.0" />
        <param name="storageCapacityFactor" value="1.0" />
        <param name="numberOfThreads" value="1" />
        <param name="mainMode" value="car"/>
        <param name="vehiclesSource" value="modeVehicleTypesFromVehiclesData"/>
        <param name="usePersonIdForMissingVehicleId" value="false"/>
        <param name="insertingWaitingVehiclesBeforeDrivingVehicles" value="true"/>
        <param name="snapshotStyle" value="queue"/>
        <param name="removeStuckVehicles" value="true"/>
        <param name="stuckTime" value="1800.0"/>
        <param name="timeStepSize" value="1.0"/>
        <param name="useLanes" value="true"/>
        <param name="trafficDynamics" value="queue"/>
    </module>

    <!-- Simulation control and output management -->
    <module name="controler">
        <param name="outputDirectory" value="./output/zero-emission-test" />
        <param name="firstIteration" value="0" />
        <param name="lastIteration" value="10" />
        <param name="writeEventsInterval" value="1" />
        <param name="writePlansInterval" value="1" />
        <param name="overwriteFiles" value="deleteDirectoryIfExists" />
        <param name="mobsim" value="qsim" />
        <param name="enableLinkToLinkRouting" value="false" />
    </module>

    <!-- Scoring parameters for activities and travel modes -->
    <module name="planCalcScore">
        <!-- Home activity parameters -->
        <parameterset type="activityParams">
            <param name="activityType" value="home" />
            <param name="typicalDuration" value="12:00:00" />
            <param name="minimalDuration" value="00:30:00" />
        </parameterset>

        <!-- Work activity parameters -->
        <parameterset type="activityParams">
            <param name="activityType" value="work" />
            <param name="typicalDuration" value="08:00:00" />
            <param name="minimalDuration" value="00:30:00" />
            <param name="openingTime" value="06:00:00" />
            <param name="closingTime" value="20:00:00" />
        </parameterset>

        <!-- Car mode parameters -->
        <parameterset type="modeParams">
            <param name="mode" value="car" />
            <param name="constant" value="0.0" />
            <param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
            <param name="marginalUtilityOfDistance_util_m" value="-0.0001" />
            <param name="monetaryDistanceRate" value="0.0" />
        </parameterset>
    </module>

    <!-- Agent strategy settings for plan selection and modification -->
    <module name="strategy">
        <param name="maxAgentPlanMemorySize" value="5" />
        
        <!-- Exploration strategy -->
        <parameterset type="strategysettings">
            <param name="strategyName" value="ChangeExpBeta"/>
            <param name="weight" value="0.6"/>
        </parameterset>
        
        <!-- Route modification strategy -->
        <parameterset type="strategysettings">
            <param name="strategyName" value="ReRoute"/>
            <param name="weight" value="0.2"/>
            <param name="disableAfterIteration" value="8"/>
        </parameterset>
        
        <!-- Time allocation modification strategy -->
        <parameterset type="strategysettings">
            <param name="strategyName" value="TimeAllocationMutator"/>
            <param name="weight" value="0.1"/>
            <param name="disableAfterIteration" value="8"/>
        </parameterset>
    </module>

    <!-- Zero Emission Zone specific configuration -->
    <module name="zeroEmissionZone">
        <!-- Network link configuration for ZEZ -->
        <param name="zoneLinks" value="3,4" />
        <param name="alternativeRoutes" value="7,8,9,10" />
        <param name="bypassRouteCapacityIncrease" value="2.0" />
        <param name="bypassRouteTravelTimeReduction" value="0.7" />

        <!-- ZEZ operational hours -->
        <param name="startTime" value="07:00:00" />
        <param name="endTime" value="19:00:00" />

        <!-- Vehicle type restrictions and charging policy -->
        <param name="allowedVehicleTypes" value="ev_car,lev_car" />
        <param name="enableGraduatedCharging" value="true" />

        <!-- Economic incentives and penalties -->
        <param name="baseCharge" value="20.0" />
        <param name="peakHourSurcharge" value="40.0" />
        <param name="evReward" value="150.0" />
        <param name="levPenalty" value="-100.0" />
        <param name="levAlternativeReward" value="200.0" />
        <param name="hevViolationPenalty" value="-500.0" />
    </module>

    <!-- Route calculation configuration -->
    <module name="planscalcroute">
        <param name="networkModes" value="car"/>
        <param name="accessEgressType" value="none" />
    </module>

    <!-- Travel time calculation settings -->
    <module name="travelTimeCalculator">
        <param name="analyzedModes" value="car" />
        <param name="separateModes" value="false" />
        <param name="travelTimeBinSize" value="900" />
        <param name="maxTime" value="108000" />
        <param name="calculateLinkTravelTimes" value="true" />
        <param name="calculateLinkToLinkTravelTimes" value="false" />
        <param name="filterModes" value="false" />
    </module>

    <!-- VSP experimental settings -->
    <module name="vspExperimental">
        <param name="vspDefaultsCheckingLevel" value="ignore" />
        <param name="writingOutputEvents" value="true" />
    </module>
</config>

=== knejadshamsi/ez-backend-turbo/src/main/resources/matsim-input/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>
    <module name="zeroEmissionZone">
        <param name="enabled" value="true" />
        <param name="zoneLinkIds" value="" />
        <param name="allowedVehicleTypes" value="" />
        <param name="policyConfiguration" value="" />
        <param name="operatingStartTime" value="07:00" />
        <param name="operatingEndTime" value="19:00" />
        <param name="lengthRestrictions" value="" />
    </module>

    <module name="network">
        <param name="inputNetworkFile" value="matsim-input/network.xml" />
    </module>

    <module name="plans">
        <param name="inputPlansFile" value="matsim-input/population.xml" />
    </module>

    <module name="transit">
        <param name="useTransit" value="true" />
        <param name="transitScheduleFile" value="matsim-input/pt/transitSchedule.xml" />
        <param name="vehiclesFile" value="matsim-input/pt/transitVehicles.xml" />
    </module>

    <module name="controler">
        <param name="outputDirectory" value="output/zero-emission-test" />
        <param name="firstIteration" value="0" />
        <param name="lastIteration" value="10" />
        <param name="writeEventsInterval" value="1" />
        <param name="writePlansInterval" value="1" />
        <param name="mobsim" value="qsim" />
    </module>

    <module name="qsim">
        <param name="startTime" value="00:00:00" />
        <param name="endTime" value="24:00:00" />
        <param name="flowCapacityFactor" value="1.0" />
        <param name="storageCapacityFactor" value="1.0" />
        <param name="numberOfThreads" value="1" />
        <param name="mainModes" value="car,pt" />
        <param name="vehicleBehavior" value="wait" />
        <param name="vehiclesSource" value="modeVehicleTypesFromVehiclesData" />
        <param name="useTransit" value="true" />
    </module>

    <module name="planCalcScore">
        <param name="learningRate" value="1.0" />
        <param name="BrainExpBeta" value="2.0" />
        <parameterset type="scoringParameters">
            <param name="lateArrival" value="-18" />
            <param name="earlyDeparture" value="-0" />
            <param name="performing" value="+6" />
            <param name="waiting" value="-0" />

            <parameterset type="modeParams">
                <param name="mode" value="car" />
                <param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
            </parameterset>

            <parameterset type="modeParams">
                <param name="mode" value="pt" />
                <param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
                <param name="constantValue" value="-1.0" />
            </parameterset>

            <parameterset type="modeParams">
                <param name="mode" value="walk" />
                <param name="marginalUtilityOfTraveling_util_hr" value="-12.0" />
                <param name="constantValue" value="-3.0" />
            </parameterset>

            <parameterset type="modeParams">
                <param name="mode" value="transit_walk" />
                <param name="marginalUtilityOfTraveling_util_hr" value="-12.0" />
                <param name="constantValue" value="-3.0" />
            </parameterset>
        </parameterset>
    </module>

    <module name="transitRouter">
        <param name="maxBeelineWalkConnectionDistance" value="1000.0" />
        <param name="searchRadius" value="1000.0" />
        <param name="extensionRadius" value="500.0" />
    </module>

    <module name="strategy">
        <param name="maxAgentPlanMemorySize" value="5" />
        <parameterset type="strategysettings">
            <param name="strategyName" value="ChangeExpBeta" />
            <param name="weight" value="0.7" />
        </parameterset>
        <parameterset type="strategysettings">
            <param name="strategyName" value="ReRoute" />
            <param name="weight" value="0.2" />
        </parameterset>
        <parameterset type="strategysettings">
            <param name="strategyName" value="ChangeTripMode" />
            <param name="weight" value="0.1" />
        </parameterset>
    </module>
</config>

=== knejadshamsi/ez-backend-turbo/matsim-defaults/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "dtd/config_v2.dtd">
<config>
    <module name="network">
        <param name="inputNetworkFile" value="network.xml" />
    </module>

    <module name="plans">
        <param name="inputPlansFile" value="population.xml" />
    </module>

    <module name="controller">
        <param name="outputDirectory" value="output" />
        <param name="firstIteration" value="0" />
        <param name="lastIteration" value="1" />
        <param name="mobsim" value="qsim" />
        <param name="routingAlgorithmType" value="FastAStarLandmarks" />
    </module>

    <module name="qsim">
        <param name="startTime" value="00:00:00" />
        <param name="endTime" value="24:00:00" />
        <param name="numberOfThreads" value="1" />
        <param name="flowCapacityFactor" value="1.0" />
        <param name="storageCapacityFactor" value="1.0" />
        <param name="stuckTime" value="10.0" />
        <param name="removeStuckVehicles" value="true" />
        <param name="insertingWaitingVehiclesBeforeDrivingVehicles" value="true" />
    </module>

    <module name="scoring">
        <param name="learningRate" value="1.0" />
        <param name="BrainExpBeta" value="2.0" />
        <param name="marginalUtilityOfMoney" value="1.0" />
        
        <parameterset type="scoringParameters">
            <param name="lateArrival" value="-18.0" />
            <param name="earlyDeparture" value="-0.0" />
            <param name="performing" value="6.0" />
            <param name="waiting" value="-0.0" />

            <parameterset type="modeParams">
                <param name="mode" value="car" />
                <param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
                <param name="monetaryDistanceRate" value="-0.0002" />
            </parameterset>
            <parameterset type="modeParams">
                <param name="mode" value="pt" />
                <param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
                <param name="monetaryDistanceRate" value="-0.0001" />
            </parameterset>
            <parameterset type="modeParams">
                <param name="mode" value="walk" />
                <param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
            </parameterset>
            <parameterset type="modeParams">
                <param name="mode" value="bike" />
                <param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
            </parameterset>
            <parameterset type="modeParams">
                <param name="mode" value="ride" />
                <param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
                <param name="monetaryDistanceRate" value="-0.0002" />
            </parameterset>

            <parameterset type="activityParams">
                <param name="activityType" value="home" />
                <param name="typicalDuration" value="12:00:00" />
            </parameterset>
            <parameterset type="activityParams">
                <param name="activityType" value="work" />
                <param name="typicalDuration" value="08:00:00" />
            </parameterset>
            <parameterset type="activityParams">
                <param name="activityType" value="shop" />
                <param name="typicalDuration" value="01:00:00" />
            </parameterset>
            <parameterset type="activityParams">
                <param name="activityType" value="leisure" />
                <param name="typicalDuration" value="02:00:00" />
            </parameterset>
        </parameterset>
    </module>

    <module name="replanning">
        <param name="maxAgentPlanMemorySize" value="5" />
        <param name="planSelectorForRemoval" value="WorstPlanSelector" />

        <parameterset type="strategysettings">
            <param name="strategyName" value="ChangeExpBeta" />
            <param name="weight" value="0.8" />
        </parameterset>
        <parameterset type="strategysettings">
            <param name="strategyName" value="ReRoute" />
            <param name="weight" value="0.2" />
        </parameterset>
        <parameterset type="strategysettings">
            <param name="strategyName" value="TimeAllocationMutator" />
            <param name="weight" value="0.1" />
        </parameterset>
    </module>

    <module name="TimeAllocationMutator">
        <param name="mutationRange" value="7200" />
    </module>

    <module name="global">
        <param name="coordinateSystem" value="EPSG:32188" />
        <param name="numberOfThreads" value="1" />
    </module>
</config>
