=== knejadshamsi/ez-backend-turbo/src/main/resources/matsim-input/dtd/emissions_v1.dtd
<!-- MATSim Emissions DTD -->

<!ELEMENT averageColdEmissionFactorFile (pollutant)*>
<!ELEMENT averageWarmEmissionFactorFile (pollutant)*>

<!ELEMENT pollutant (segment)*>
<!ATTLIST pollutant
          name          CDATA                    #REQUIRED>

<!ELEMENT segment ((parkingTime|speed))*>
<!ATTLIST segment
          type         CDATA                    #REQUIRED
          fuel         CDATA                    #REQUIRED>

<!ELEMENT parkingTime EMPTY>
<!ATTLIST parkingTime
          value        CDATA                    #REQUIRED
          unit         CDATA                    #REQUIRED
          amount       CDATA                    #REQUIRED>

<!ELEMENT speed EMPTY>
<!ATTLIST speed
          value        CDATA                    #REQUIRED
          unit         CDATA                    #REQUIRED
          amount       CDATA                    #REQUIRED>

=== knejadshamsi/ez-backend-turbo/src/main/resources/matsim-input/emissions/sample_coefficients/cold_emissions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE averageColdEmissionFactorFile SYSTEM "../../dtd/emissions_v1.dtd">
<averageColdEmissionFactorFile>
    <pollutant name="CO">
        <segment type="PASSENGER_CAR" fuel="PETROL">
            <parkingTime value="0.0" unit="h" amount="20.0" unit="g/start"/>
            <parkingTime value="1.0" unit="h" amount="25.0" unit="g/start"/>
            <parkingTime value="2.0" unit="h" amount="30.0" unit="g/start"/>
        </segment>
        <segment type="PASSENGER_CAR" fuel="DIESEL">
            <parkingTime value="0.0" unit="h" amount="15.0" unit="g/start"/>
            <parkingTime value="1.0" unit="h" amount="20.0" unit="g/start"/>
            <parkingTime value="2.0" unit="h" amount="25.0" unit="g/start"/>
        </segment>
    </pollutant>
</averageColdEmissionFactorFile>

=== knejadshamsi/ez-backend-turbo/src/main/resources/matsim-input/emissions/sample_coefficients/warm_emissions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE averageWarmEmissionFactorFile SYSTEM "../../dtd/emissions_v1.dtd">
<averageWarmEmissionFactorFile>
    <pollutant name="CO">
        <segment type="PASSENGER_CAR" fuel="PETROL">
            <speed value="0.0" unit="km/h" amount="100.0" unit="g/km"/>
            <speed value="30.0" unit="km/h" amount="20.0" unit="g/km"/>
            <speed value="50.0" unit="km/h" amount="10.0" unit="g/km"/>
        </segment>
        <segment type="PASSENGER_CAR" fuel="DIESEL">
            <speed value="0.0" unit="km/h" amount="90.0" unit="g/km"/>
            <speed value="30.0" unit="km/h" amount="15.0" unit="g/km"/>
            <speed value="50.0" unit="km/h" amount="8.0" unit="g/km"/>
        </segment>
    </pollutant>
</averageWarmEmissionFactorFile>
